### ISSUE TITLE
design idea

### ISSUE THREAD

**Issue by Araq** [termermc/nim-stack-strings#2]
Instead of providing `trySetLen` and some procs that produce exceptions and some that don't, consider this design instead: Data that does not fit the string is cut off and the string is made to end in \0xff or similar so that it's easy enough to see that a cut had been made. This is almost what Turbo Pascal did except that it added no visible marker.

**Comment by termermc** [comment]
There's a proc called `addTruncate` which does almost what you're saying, minus the terminator. That does remind me though, Beef was suggesting to me that I make strings null-terminated under the hood for ease of use with C. I'm not sure if that's something I want to do uniformly, but I was considering having a conditional compilation flag for null terminated strings. What do you think?

**Comment by Araq** [comment]
It's a bad idea, avoid. Clients of your libraries must then agree on the state of compilation flag.

**Comment by beef331** [comment]
Using a compilation flag is a horrible idea indeed, I more meant doing it globally or encoding it into a type.
```nim
type
  StackStringImpl[Size: static int, isTerminated: static bool] = object
    ...
  StackString[Size: static int] = StackStringImpl[Size, false]
  NulledStackString[Size: static int] = StackStringImpl[Size, True]
```

**Comment by Araq** [comment]
Sounds like overkill to me. Just make it zero terminated and then it can be passed to C strings.

**Comment by termermc** [comment]
Yeah, I'm thinking null-terminated is the best ultimately, since I expect a lib like this would end up being used in environments where you're passing strings to and from C. Are normal Nim strings null-terminated? @Araq

**Comment by beef331** [comment]
Yes normal Nim strings are null terminated, almost every sane string is.

**Comment by termermc** [comment]
@beef331 Seems like a legacy thing that stuck and became necessary

**Comment by Araq** [comment]
Correct but there are more important fights to win. ;-)

**Comment by termermc** [comment]
@Araq @beef331 Done
